### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '$$')

### ISSUE THREAD

**Issue by JPustkuchen** [jfeltkamp/cookiesjsr#35] opened 2024-12-15 11:30 UTC
Still with 2.0.2 I get the following error on a Drupal project in latest Chrome on Windows 11, reloading the page with F5 without having consent given or not:

```
cookiesjsr.min.js?v=10.3.10:12 Uncaught TypeError: Cannot read properties of undefined (reading '$$')
    at z (cookiesjsr.min.js?v=10.3.10:12:5387)
    at new jn (cookiesjsr.min.js?v=10.3.10:12:33329)
    at cookiesjsr.min.js?v=10.3.10:12:33351
```

On first page load, the banner appears, on second page load it's not shown, but this Error appears in log, so I'd rate it as major issue.

**Comment by JPustkuchen** [comment] 2024-12-15 11:31
This is, where it fails:
```
const u = n.$$ = {
        fragment: null,
        ctx: [],
        props: r,
        update: L,
        not_equal: i,
        bound: Ue(),
        on_mount: [],
        on_destroy: [],
        on_disconnect: [],
        before_update: [],
        after_update: [],
        context: new Map(e.context || (o ? o.$$.context : [])),
        callbacks: Ue(),
        dirty: l,
        skip_bound: !1,
        root: e.target || o.$$.root // <<<<<<<<<<<<<<<<<<<<<TypeError: Cannot read properties of undefined (reading '$$')
    };
```

**Comment by JPustkuchen** [comment] 2024-12-15 11:33
Maybe we could just use optional chaining? `?.`?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

`root: e.target || o?.$$?.root`

But I think we should better understand why o.$$ is not defined for the root cause?

**Comment by JPustkuchen** [comment] 2024-12-15 11:35
Update: Sorry, seems I forgot to manually flush caches. This might be gone already? At least I'm now no more able to reproduce it.

I'll leave this one open for @jfeltkamp to confirm, because it didn't happen on every page load, might also be a race condition. So let's better be sure it's solved code-wise.

**Comment by jfeltkamp** [comment] 2024-12-15 11:41
@JPustkuchen: I updated Svelte from 3.xx to 5.xx for the last tag 2.0.2. I think the issue should be gone. I found an Svelte issue here that matches our problem: https://github.com/sveltejs/svelte/issues/6600
It relates to Svelte version 3.38.1

I'll check this twice.

**Comment by JPustkuchen** [comment] 2024-12-15 13:01
https://github.com/jfeltkamp/cookiesjsr/issues/36 is the follow-up that happens now.

**Comment by jfeltkamp** [comment] 2024-12-16 09:48
@JPustkuchen  Failing code originated from Svelte is replaced.
The reason for the issue is clearified (script in example page is loaded async in the header not as required with defer or before closing body tag)
I think this ticket can be closed. (Please re-open, when something is missing.)

**Closed as completed by jfeltkamp** 2024-12-16 09:48 UTC
